USE FREERIDER_DB;

DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
    ID INT NOT NULL,
    NAME VARCHAR(60),
    CONTACTS VARCHAR(60),
    STATUS ENUM('Active', 'InRegistration', 'Terminated'),
    PRIMARY KEY (ID)
);

CREATE TABLE VEHICLE (
    ID INT NOT NULL,
    MAKE VARCHAR(60),
    MODEL VARCHAR(60),
    SEATS INT DEFAULT 4,
    CATEGORY ENUM('Sedan', 'SUV', 'Convertible', 'Van', 'Bike'),
    POWER ENUM('Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Hydrogen'),
    STATUS ENUM('Active', 'Serviced', 'Terminated'),
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION (
    ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    VEHICLE_ID INT NOT NULL,
    BEGIN DATETIME,
    END DATETIME,
    PICKUP VARCHAR(48),
    DROPOFF VARCHAR(48),
    STATUS ENUM('Inquired', 'InquiryConfirmed', 'Booked', 'Cancelled'),
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(ID)
);